"""create households and memberships

Revision ID: f74a10104974
Revises: 9d8aadccb81c
Create Date: 2026-07-17 00:31:08.658013

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f74a10104974"
down_revision: str | Sequence[str] | None = "9d8aadccb81c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "households",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_households_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_households")),
    )
    op.create_index(
        op.f("ix_households_created_by_user_id"), "households", ["created_by_user_id"], unique=False
    )
    op.create_table(
        "household_memberships",
        sa.Column("household_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role", sa.Enum("owner", "parent", "child", name="household_role"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_household_memberships_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_household_memberships_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_household_memberships")),
        sa.UniqueConstraint(
            "household_id", "user_id", name="uq_household_memberships_household_user"
        ),
    )
    op.create_index(
        op.f("ix_household_memberships_household_id"),
        "household_memberships",
        ["household_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_household_memberships_user_id"), "household_memberships", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_household_memberships_user_id"), table_name="household_memberships")
    op.drop_index(op.f("ix_household_memberships_household_id"), table_name="household_memberships")
    op.drop_table("household_memberships")
    op.drop_index(op.f("ix_households_created_by_user_id"), table_name="households")
    op.drop_table("households")
    # ### end Alembic commands ###
